### ISSUE TITLE
Error when adding a youtube playlist 

### ISSUE THREAD

**Issue by 5wi5wi** [ThatGuyJacobee/Elite-Music#87] opened 2024-06-13 10:11 UTC
### the title
adding a single song has no issues.

Win11
Self-hosting without any apps

```
DiscordAPIError[10062]:` Unknown interaction
    at handleErrors (C:\Users\-------\OneDrive - MKHB\Desktop\Elite-Music-1.5\node_modules\@discordjs\rest\dist\index.js:730:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async BurstHandler.runRequest (C:\Users\-------\OneDrive - MKHB\Desktop\Elite-Music-1.5\node_modules\@discordjs\rest\dist\index.js:835:23)
    at async _REST.request (C:\Users\-------\OneDrive - MKHB\Desktop\Elite-Music-1.5\node_modules\@discordjs\rest\dist\index.js:1278:22)
    at async ChatInputCommandInteraction.deferReply (C:\Users\-------\OneDrive - MKHB\Desktop\Elite-Music-1.5\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:71:5)
    at async Object.execute (C:\Users\-------\OneDrive - MKHB\Desktop\Elite-Music-1.5\commands\music\play.js:40:13)
    at async Object.execute (C:\Users\-------\OneDrive - MKHB\Desktop\Elite-Music-1.5\events\interactionCreate.js:37:17) {
  requestBody: { files: undefined, json: { type: 5, data: [Object] } },
  rawError: { message: 'Unknown interaction', code: 10062 },
  code: 10062,
  status: 404,
  method: 'POST',
  url: 'https://discord.com/api/v10/interactions/1250752752850571325/aW50ZXJhY3Rpb246MTI1MDc1Mjc1Mjg1MDU3MTMyNTpnRFhKaW1KVTNOMWxHdkJma3d2NlBZNmlJU2xCUUZ0UXg0bmR5bEZVR3pvNEloMFZ5TklTNXBZQTBGeWxGVDRpaDZVTHFuOUh1V0RUWTZzWlRFYVA5VTh3S0VjbXlQRWlNSW41a1I1eWRvYkluMkZsNzdIOXYzclBoNWtoNkt6Tw/callback'
}
Error [InteractionNotReplied]: The reply to this interaction has not been sent or deferred.
    at ChatInputCommandInteraction.followUp (C:\Users\Aziz.5wi\OneDrive - MKHB\Desktop\Elite-Music-1.5\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:187:64)
    at Object.execute (C:\Users\-------\OneDrive - MKHB\Desktop\Elite-Music-1.5\commands\music\play.js:93:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.execute (C:\Users\-------\OneDrive - MKHB\Desktop\Elite-Music-1.5\events\interactionCreate.js:37:17) {
  code: 'InteractionNotReplied'
}
Caught Exception: DiscordAPIError[10062]: Unknown interaction
    at handleErrors (C:\Users\-------\OneDrive - MKHB\Desktop\Elite-Music-1.5\node_modules\@discordjs\rest\dist\index.js:730:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async BurstHandler.runRequest (C:\Users\-------\OneDrive - MKHB\Desktop\Elite-Music-1.5\node_modules\@discordjs\rest\dist\index.js:835:23)
    at async _REST.request (C:\Users\-------\OneDrive - MKHB\Desktop\Elite-Music-1.5\node_modules\@discordjs\rest\dist\index.js:1278:22)
    at async ChatInputCommandInteraction.reply (C:\Users\-------\OneDrive - MKHB\Desktop\Elite-Music-1.5\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:114:5)
    at async Object.execute (C:\Users\-------\OneDrive - MKHB\Desktop\Elite-Music-1.5\events\interactionCreate.js:43:17)
-----------------------------------------------------------------------------------------------------------------------------------
```

**Comment by ThatGuyJacobee** [comment] 2024-07-01 02:54
Hi there! Apologies for the late reply, I must have missed both of the issues in the gh notification spam :)

Is this playlist issue occurring on a specific platform, such as YouTube or Spotify? 

In regards to troubleshooting, begin by attempting to update your dependencies. I've just pushed a commit which bumps dependencies, so make sure to pull this (or just replace package.json manually) and then run `npm install` at the root directory.

Looking forward to your reply!

**Comment by ThatGuyJacobee** [comment] 2024-07-01 02:59
Could you please also add the following segment of code to the bottom of your `index.js` file.

Now with this saved, try playing the playlist again and you should see a ton of logs being printed in your console. Please send this over as it will likely have some valuable information regarding the culprit of this issue. 🙂

**Logs Snippet:**
```javascript
console.log(player.scanDeps());player.on('debug',console.log).events.on('debug',(_,m)=>console.log(m));
```

**Comment by 5wi5wi** [comment] 2024-07-03 07:27
```
GuildQueue initialized for guild Galaxy Revolution (ID: 764548803067379712)
Searching https://www.youtube.com/playlist?list=PLu1rCq-UwgMWXNiGUhhio4DstEKcf2IGG
Search engine set to auto, fallback search engine set to autoSearch
Protocol https detected in query
Could not find an extractor that supports https protocol. Falling back to default behavior...
Query type identified as youtubePlaylist
Checking cache...
Cache miss for query https://www.youtube.com/playlist?list=PLu1rCq-UwgMWXNiGUhhio4DstEKcf2IGG
Executing extractors...
Executing extractor com.discord-player.spotifyextractor...
Executing extractor com.discord-player.applemusicextractor...
Executing extractor com.discord-player.soundcloudextractor...
Executing extractor com.discord-player.youtubeextractor...
Extractor com.discord-player.youtubeextractor executed successfully!
Executing metadata query using com.discord-player.youtubeextractor extractor...
Metadata query was successful!
Adding data to cache...
DiscordAPIError[10062]: Unknown interaction
    at handleErrors (C:\Users\user\OneDrive\Desktop\Elite-Music\node_modules\@discordjs\rest\dist\index.js:730:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async BurstHandler.runRequest (C:\Users\user\OneDrive\Desktop\Elite-Music\node_modules\@discordjs\rest\dist\index.js:835:23)
    at async _REST.request (C:\Users\user\OneDrive\Desktop\Elite-Music\node_modules\@discordjs\rest\dist\index.js:1278:22)
    at async ChatInputCommandInteraction.deferReply (C:\Users\user\OneDrive\Desktop\Elite-Music\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:71:5)
    at async Object.execute (C:\Users\user\OneDrive\Desktop\Elite-Music\commands\music\play.js:40:13)
    at async Object.execute (C:\Users\user\OneDrive\Desktop\Elite-Music\events\interactionCreate.js:37:17) {
  requestBody: { files: undefined, json: { type: 5, data: [Object] } },
  rawError: { message: 'Unknown interaction', code: 10062 },
  code: 10062,
  status: 404,
  method: 'POST',
  url: 'https://discord.com/api/v10/interactions/1257959180787122227/aW50ZXJhY3Rpb246MTI1Nzk1OTE4MDc4NzEyMjIyNzpJUU1wdjVDd0Z6OVFMRWg4WVZpcjlFdGZlZ3VKYW1yOFdKUFVXMG4wcEJOMFU4WXhSUzhEQkRxUnlXeUhMaWxuNW1BVWdGY2dYVUhTOFBHMDh1NDZLVXpJNEJxeFEwMllQNGhYd1ZTZ0k2d2Z3VEtOVnpLVTZMSjA1MU56ZUlySw/callback'
}
Error [InteractionNotReplied]: The reply to this interaction has not been sent or deferred.
    at ChatInputCommandInteraction.followUp (C:\Users\user\OneDrive\Desktop\Elite-Music\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:187:64)
    at Object.execute (C:\Users\user\OneDrive\Desktop\Elite-Music\commands\music\play.js:93:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.execute (C:\Users\user\OneDrive\Desktop\Elite-Music\events\interactionCreate.js:37:17) {
  code: 'InteractionNotReplied'
}
Caught Exception: DiscordAPIError[10062]: Unknown interaction
    at handleErrors (C:\Users\user\OneDrive\Desktop\Elite-Music\node_modules\@discordjs\rest\dist\index.js:730:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async BurstHandler.runRequest (C:\Users\user\OneDrive\Desktop\Elite-Music\node_modules\@discordjs\rest\dist\index.js:835:23)
    at async _REST.request (C:\Users\user\OneDrive\Desktop\Elite-Music\node_modules\@discordjs\rest\dist\index.js:1278:22)
    at async ChatInputCommandInteraction.reply (C:\Users\user\OneDrive\Desktop\Elite-Music\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:114:5)
    at async Object.execute (C:\Users\user\OneDrive\Desktop\Elite-Music\events\interactionCreate.js:43:17)
    
```

this is the log

**Comment by ThatGuyJacobee** [comment] 2024-08-21 20:57
Hey, I completely missed this reply, deeply apologise. Is this still occurring?

There was a range of bug fixes and dependency bumps in the past few weeks which I recommend pulling and seeing if the issue still persists. ✌️

**Comment by 5wi5wi** [comment] 2024-08-22 02:20
> Hey, I completely missed this reply, deeply apologise. Is this still occurring?
> 
> There was a range of bug fixes and dependency bumps in the past few weeks which I recommend pulling and seeing if the issue still persists. ✌️

Ok, I will do that

**Comment by 5wi5wi** [comment] 2024-08-22 16:46
same issue, I think.
```
DiscordAPIError[40060]: Interaction has already been acknowledged.
    at handleErrors (C:\Users\Aziz-PC\Desktop\Elite-Music\node_modules\@discordjs\rest\dist\index.js:730:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async BurstHandler.runRequest (C:\Users\Aziz-PC\Desktop\Elite-Music\node_modules\@discordjs\rest\dist\index.js:835:23)
    at async _REST.request (C:\Users\Aziz-PC\Desktop\Elite-Music\node_modules\@discordjs\rest\dist\index.js:1278:22)
    at async ChatInputCommandInteraction.deferReply (C:\Users\Aziz-PC\Desktop\Elite-Music\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:71:5)
    at async Object.execute (C:\Users\Aziz-PC\Desktop\Elite-Music\commands\music\play.js:40:13)
    at async Object.execute (C:\Users\Aziz-PC\Desktop\Elite-Music\events\interactionCreate.js:37:17) {
  requestBody: { files: undefined, json: { type: 5, data: [Object] } },
  rawError: {
    message: 'Interaction has already been acknowledged.',
    code: 40060
  },
  code: 40060,
  status: 400,
  method: 'POST',
  url: 'https://discord.com/api/v10/interactions/1276220753783685161/aW50ZXJhY3Rpb246MTI3NjIyMDc1Mzc4MzY4NTE2MTpRYXk1MlJHM256b1BHR3VNQ3NwUURlaVJUSG1ONkFLZWthcVFUOTVIYzFoM2lYenhnYzZRY0xjSVU2UzJ6UWNGUVNJZTB0SXFTdDJRdGpLYkhYZDF4WTdrT3JaRUhSZDllcUZrWGhCWmwzQ1NYMXNPQ1lrTnliVVoydDJFRm5xZg/callback'
}
Error [InteractionNotReplied]: The reply to this interaction has not been sent or deferred.
    at ChatInputCommandInteraction.followUp (C:\Users\Aziz-PC\Desktop\Elite-Music\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:187:64)
    at Object.execute (C:\Users\Aziz-PC\Desktop\Elite-Music\commands\music\play.js:93:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.execute (C:\Users\Aziz-PC\Desktop\Elite-Music\events\interactionCreate.js:37:17) {
  code: 'InteractionNotReplied'
}
Caught Exception: DiscordAPIError[40060]: Interaction has already been acknowledged.
    at handleErrors (C:\Users\Aziz-PC\Desktop\Elite-Music\node_modules\@discordjs\rest\dist\index.js:730:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async BurstHandler.runRequest (C:\Users\Aziz-PC\Desktop\Elite-Music\node_modules\@discordjs\rest\dist\index.js:835:23)
    at async _REST.request (C:\Users\Aziz-PC\Desktop\Elite-Music\node_modules\@discordjs\rest\dist\index.js:1278:22)
    at async ChatInputCommandInteraction.reply (C:\Users\Aziz-PC\Desktop\Elite-Music\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:114:5)
    at async Object.execute (C:\Users\Aziz-PC\Desktop\Elite-Music\events\interactionCreate.js:43:17)
   
```

**Comment by ThatGuyJacobee** [comment] 2024-08-26 11:58
Hmmm, I can't reproduce this on my end with the same playlist you used, as it plays as expected.

Some extra troubleshooting steps:
- Are you sure that you are only running one instance of the bot at a time (on the same bot token)?
- Can you confirm that `@distube/ytdl-core` in your `package.json` is set to `^4.14.4`?
- Send me the top `dependencies` part of your `package.json`, just to double confirm it is definitely not a dependency issue.

**Comment by ThatGuyJacobee** [comment] 2024-09-13 00:16
Since it has been a while, I will be closing this issue for now. Feel free to reply again with the above troubleshooting steps. 👍

**Closed by ThatGuyJacobee** 2024-09-13 00:16 UTC
